// Copyright 2023 rshulabs <2505269010@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int ./internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `
func init() {
	register(ErrSuccess, 200, "OK")
	register(ErrUnknown, 500, "Internal server error")
	register(ErrValidation, 400, "Validation failed")
	register(ErrNotFound, 404, "Page not found")
	register(ErrTokenInvalid, 401, "Token invalid")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct")
	register(ErrDatabase, 500, "Database error")
	register(ErrEncrypt, 401, "Error occurred while encrypting the user password")
	register(ErrSignatureInvalid, 401, "Signature invalid")
	register(ErrInvalidAuthHeader, 401, "Invalid authorization header")
	register(ErrMissingHeader, 401, "Missing authorization header")
	register(ErrPasswordIncorrect, 401, "Password incorrect")
	register(ErrPermissionDenied, 403, "Permission denied")
	register(ErrBlackListCheck, 401, "Black list check failed")
	register(ErrGuardTokenCheck, 401, "Guard token check failed")
	register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")
	register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")
	register(ErrInvalidJSON, 500, "Invalid json data")
	register(ErrEncodingJSON, 500, "JSON data could not be encoded")
	register(ErrDecodingJSON, 500, "JSON data could not be decoded")
	register(ErrInvalidYaml, 500, "Invalid yaml data")
	register(ErrEncodingYaml, 500, "YAML data could not be encoded")
	register(ErrDecodingYAML, 500, "YAML data could not be decoded")
}
