version: "3.5"
services:
  etcd:
    hostname: etcd
    container_name: etcd
    image: bitnami/etcd:3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    #   - "4001:4001"
    #   - "7001:7001"
    privileged: true
    volumes:
      - "/root/workspace/go/app/HgCache/build_tools/etcd/data:/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      #参数指不用密码可以连接
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    ports:
      - 2379:2379
      - 2380:2380
    # networks:
    #   - etcdnet
  etcd-keeper:
    image: evildecay/etcdkeeper
    container_name: etcd-keeper
    ports:
      - 8090:8080
    environment:
      - ETCD_SERVERS=http://192.168.60.34:2379
    # networks:
    #   - etcdnet
# networks:
#   etcdnet:
#     name: etcdnet
